package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"graphql/graph/model"
)

// CreateCompany is the resolver for the createCompany field.
func (r *mutationResolver) CreateCompany(ctx context.Context, input model.NewCompany) (*model.Company, error) {
	company := &model.Company{
		CompanyName: input.CompanyName,
		FoundedYear: input.FoundedYear,
		Location:    input.Location,
		// Assuming there's no association with User in this context.
	}

	return r.S.CreateCompany(company)
}

// CreateJob is the resolver for the createJob field.
func (r *mutationResolver) CreateJob(ctx context.Context, input model.NewJob) (*model.Job, error) {
	job := &model.Job{
		ID:                 input.CompanyID,
		Title:              input.Title,
		ExperienceRequired: input.ExperienceRequired,
		CompanyID:          input.CompanyID,
	}

	return r.S.CreateJob(job)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
